### ISSUE TITLE
"Sequence contains no matching element" when attempting to config in ASP.Net web project

### ISSUE THREAD

**Issue by mattdrewitt** [graffen/NLog.Targets.Syslog#76]
Having an issue upgrading to version NLog.Targets.Syslog 3.0+ in an ASP.Net project.  Made a brand new one for testing, only added this package and its dependancies, received the following error when trying to generate a `new MessageBuilderConfig()` that appears to be related to either of the RFC configs 

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at NLog.Targets.Syslog.Extensions.StackTraceExtensions.EntryAssembly(StackTrace stackTrace)
   at NLog.Targets.Syslog.Settings.UniversalAssembly.EntryAssembly()
   at NLog.Targets.Syslog.Settings.Rfc3164Config..ctor()
   at NLog.Targets.Syslog.Settings.MessageBuilderConfig..ctor()
   at WebApplication1.Controllers.AccountController.Login(String returnUrl) in C:\\Workspace\\TestingApp\\WebApplication\\Controllers\\AccountController.cs:line 75
```

**Comment by mattdrewitt** [comment]
I have added a PR to patch the issue.  I tried to keep the existing functionality the same, but making it a bit safer. https://github.com/graffen/NLog.Targets.Syslog/pull/77
