### ISSUE TITLE
Intermittent connection aborted exception

### ISSUE THREAD

**Issue by AnturGyffrous** [graffen/NLog.Targets.Syslog#98]
We are using [NLog.Targets.Syslog](https://github.com/graffen/NLog.Targets.Syslog) version 4.0.0 to log approximately 20-30Mb of log entries a day from half a dozen or so machines.

However, we are regularly seeing a `System.IO.IOException` exception in the NLog `internalLogFile` with the message "*Unable to write data to the transport connection*" and an inner exception of type `System.Net.Sockets.SocketException` with the message "*An established connection was aborted by the software in your host machine*"

Here's an example stack trace:

    2017-08-11 08:35:39.0636 Warn Task faulted Exception: System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
       at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
       at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
       --- End of inner exception stack trace ---
       at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
       at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
       at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
       at System.Net.Security._SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
       at NLog.Targets.Syslog.Extensions.TaskExtensions.SafeFromAsync[TArg1,TArg2,TArg3](TaskFactory taskFactory, Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)

Is there anything you can think of we can do to improve the resilience of the connection, or that we might be doing wrong that is causing this issue?

**Comment by luigiberrettini** [comment]
The stack trace suggests that the issue should not be related with NLog.Targets.Syslog source code.
Moreover the connection is already resilient, in fact it is reopened on failure.

I think that you are looking for a way to mitigate/remove network failures be them related with your machine/OS configuration or the network itself.

I hope that with one or more of the following steps you could detect what is wrong and solve the issue:
1. test the target on a local machine
2. test the target on a machine that is an exact copy of the production one 
3. use UDP
4. use TCP disabling TLS
5. disable keep-alive
6. tune keep-alive timeout and interval
7. disable antivirus
8. disable firewall
9. use a network sniffer to see if packets are sent and what's being sent

**Comment by luigiberrettini** [comment]
Closing: should you need further help please ask for it in this issue
